export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.jpg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/yoga.avif',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/bulb.jpg',
        prompt:''
    },
]